# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1dee8495f47eb9aef37c576ae5087e11ff26606719eb56c1b11c7fb12eb892e6e69114f163b936777839432d8f6e5046e7e9e619441bf70460e954b91811241

test:
  secret_key_base: 9f7dc81dd60d58d4f9ae848b974bbf49913c20185ee73cb09ae6e797ba62eb111512ff22c7dbfd7f16ce3b97334ce29e4e1ad2482e8c86e7d61dc6db50b1ae72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
